language: java
sudo: false
before_install: git clone -b travis `git config --get remote.origin.url` ${HOME}/travis
services:
- docker
addons:
  apt:
    packages:
    - rpm
cache:
  directories:
  - "$HOME/.m2"
install:
- mvn compile -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B
  -V
script: travis_wait 120 ./travis-script.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn site
  site:stage scm-publish:publish-scm --settings ${HOME}/travis/settings.xml -B -V
branches:
  except:
  - travis
  - gh-pages
env:
  global:
  - secure: J+lRFlE7ISkg362ROM7TeEg2+C8YGM0H4pimlEaf6g9e7QiT4zidpDxH6v9cOHl7B5hFiZ8K6CizfBpwq5AFrWfpPCO22VZMj4oX6tAKsD6AEeDt6x8dxcpx0aiRYrwnARKCucPnLCLWKSEor3BkO+v8LHAw9YMGOk770B64hIs=
  - secure: F5dtEzxr/SpXui6DDqQVJkdOqt97TaLe9r39l0Bw2FM9yY1vUeIliMhYbMQgKUl5Kk2/G4MGSuNShcKis1u9HxRKOMWtkRXddhkqGoHPUbUoImV2SBwUu4Nw/We70dTAR+TQIZoYkcoRNKAHGPzlOhs3GUuyUglS1/CtrcbWb5Y=
  - secure: ObJBI3RnSfv4ajoXqg2OPHg8TYDW0Y3vf2b2vVt4c6VUiFo4fzuTf/WcS5GwgIbNBnyIRcTmAxg6OFYfLiztyXWDyyhF+JekHd5lUTJqSpGU0p+s/otj83Rlp0YxFabyCx2DYjUIRB1EvGRp6zjcywi+J6e0MbvDCsQZ3p+0bGc=
  - secure: W8MmwrVpkN+4D3XQwTPdgwCdHKR41U1KJxDgaGOTaWAK/QYPDI86mocegNI7idAPd3X+MeinO8mVKCF3iQw4n9F/x+C1Z5f8R+BDwPO8rP2mwcez7m7JUDInVpFRDfXyM9+cWYCLsUiT5w/pkOoQi0e2+M8+s5mP8fRZauDk6rQ=
  - secure: NDtznKLgAjAGiNeMjReiD8Oaz1+p/erYIHBK/bFOGASH2MHljz2ozxKzMUhiJqx7VAR47M28jMZr38CRD+ATXDw5jbrki6CJqAujmi1afIK7hPQOU8E6jiDL0a/kVHQ402CySL+cF/PXhoNiNZbZlMpPcVUL8vCEBq9uzKx90CA=
  - secure: aVsw/zSi7VrW/rU5yzeCpL2aC09of8hgO12mASBW4jn8SXS6J3a9Vxx6bHHSNqWiBys/TTw4WSXv0QX2FU0hbMBUitw6wT5zMikLPJPoI57/JwbRG1kXvNKl1v2efP2wm04qlvJPhhUlzo/eIQJlWDE590sZ8lo8FdoDOx986cQ=
